In [ ]:
#Created by:Upadhi Vijay, 
#email : upadhi_vijay@berkeley.edu

In [1]:
import pandas as pd 
import sqlalchemy as sa
from sqlalchemy.orm import sessionmaker

In [2]:
#creating database connection 
engine = sa.create_engine('mysql+mysqlconnector://root:123456@localhost/mydb', pool_size=25, max_overflow=10, pool_timeout=60,pool_recycle=3600) 
Session = sessionmaker(bind=engine)

In [3]:
#Import cities data
query = "SELECT * FROM mbta_e_data ;"
route_data = pd.read_sql(query, engine).drop(columns = "index")
route_data.head()

,route_id,VKT,num_buses,avg_rider,energy_30ft,energy_40ft,energy_60ft,avg_speed,30ft_LOS,40ft_LOS,60ft_LOS,diesel_LOS,fuel_economy,e_emi30ft,e_emi40ft,e_emi60ft,d_emi,pm_emi
0,201,671.572,4.0,10.0,1391.904644,1768.149663,2428.823606,5.920670,no,no,no,yes,2.129226,17.147412,21.782520,29.921618,138.771094,391.526476
1,202,204.479,6.0,10.0,393.132635,499.785551,687.064708,5.179345,no,no,no,yes,1.996692,4.843153,6.157052,8.464216,44.355691,119.211257
2,210,533.152,4.0,11.0,1149.806222,1461.450040,2008.648337,7.328337,no,no,no,yes,2.371208,14.164908,18.004169,24.745316,104.494883,310.827616
3,211,804.990,9.0,17.0,1351.234773,1706.557173,2330.542098,6.300936,no,no,no,yes,2.195845,16.646384,21.023738,28.710850,191.687627,469.309170
4,212,189.424,2.0,17.0,341.131084,428.283673,581.364908,5.997131,no,no,no,yes,2.142695,4.202526,5.276192,7.162059,45.812361,110.434192

In [4]:
#estimating fuel economy 
route_data["fuel_economy"] = -0.0032* (route_data["avg_speed"]**2) +0.2143*route_data["avg_speed"]+0.9726

In [5]:
route_data

,route_id,VKT,num_buses,avg_rider,energy_30ft,energy_40ft,energy_60ft,avg_speed,30ft_LOS,40ft_LOS,60ft_LOS,diesel_LOS,fuel_economy,e_emi30ft,e_emi40ft,e_emi60ft,d_emi,pm_emi
0,201,671.572,4.0,10.0,1391.904644,1768.149663,2428.823606,5.920670,no,no,no,yes,2.129226,17.147412,21.782520,29.921618,138.771094,391.526476
1,202,204.479,6.0,10.0,393.132635,499.785551,687.064708,5.179345,no,no,no,yes,1.996692,4.843153,6.157052,8.464216,44.355691,119.211257
2,210,533.152,4.0,11.0,1149.806222,1461.450040,2008.648337,7.328337,no,no,no,yes,2.371208,14.164908,18.004169,24.745316,104.494883,310.827616
3,211,804.990,9.0,17.0,1351.234773,1706.557173,2330.542098,6.300936,no,no,no,yes,2.195845,16.646384,21.023738,28.710850,191.687627,469.309170
4,212,189.424,2.0,17.0,341.131084,428.283673,581.364908,5.997131,no,no,no,yes,2.142695,4.202526,5.276192,7.162059,45.812361,110.434192
5,214,322.743,4.0,40.0,544.630753,680.983114,920.342054,6.568696,no,no,no,yes,2.242199,6.709517,8.389295,11.338050,114.226454,188.159169
6,215,1395.334,12.0,20.0,2161.350609,2718.171950,3696.158497,6.819996,no,no,no,yes,2.285286,26.626515,33.486212,45.534407,345.699171,813.479722
7,216,807.525,4.0,18.0,1237.950480,1567.417746,2145.925622,8.105051,no,no,no,yes,2.499298,15.250791,19.309626,26.436488,181.735827,470.787075
8,217,114.998,2.0,26.0,218.786761,274.744028,373.019999,6.939686,no,no,no,yes,2.305665,2.695319,3.384678,4.595378,31.911552,67.043834
9,220,2756.083,7.0,18.0,3915.932731,4936.985155,6730.115766,10.125741,no,no,no,yes,2.814448,48.241891,60.820631,82.910901,579.528448,1606.796389
10,221,74.948,2.0,12.0,124.897282,158.060413,216.297502,8.276027,no,no,no,yes,2.526976,1.538658,1.947207,2.664653,14.434107,43.694684
11,222,1993.842,5.0,23.0,2616.254029,3295.400648,4488.021977,9.160976,no,no,no,yes,2.667242,32.230646,40.597316,55.289680,483.687584,1162.409886
12,225,1479.408,4.0,28.0,3056.227631,3831.944344,5194.381756,5.499128,no,no,no,yes,2.054294,37.650851,47.207206,63.991599,451.728693,862.494864
13,226,799.607,2.0,25.0,1713.363383,2156.449377,2934.540525,8.399351,no,no,no,yes,2.546824,21.107587,26.566135,36.151741,206.921012,466.170881
14,230,1854.350,5.0,25.0,3366.430502,4231.808063,5751.607846,7.921780,no,no,no,yes,2.469423,41.472360,52.133282,70.856283,487.394485,1081.086050
15,236,692.657,2.0,23.0,1449.444698,1823.766271,2481.257859,7.455959,no,no,no,yes,2.392520,17.856270,22.467683,30.567576,177.869424,403.819031
16,238,1901.825,14.0,28.0,3639.111875,4562.969337,6185.476180,8.195297,no,no,no,yes,2.513931,44.831628,56.212985,76.201275,524.870709,1108.763975
17,240,2698.432,11.0,35.0,5322.178789,6630.882784,8928.983719,8.762124,no,no,no,yes,2.604644,65.565981,81.688412,109.999607,830.040308,1573.185856
18,245,373.227,3.0,16.0,750.315367,951.332318,1304.384023,7.492085,no,no,no,yes,2.398534,9.243425,11.719831,16.069212,82.206444,217.591341

## Estimating emissions from operations

The emissions from diesel and electric bus operations are divided in two parts. The fuel cycle consists of Well to Pump and Pump to Wheel emissions. The vehicle cycle consists of emissions due to vehicle manufacturing and other external components such as battery.

In [6]:
#Estimating emissions for electric buses 
#Fuel cycle emissions 
wtp = {"diesel":  16,  "electric":  0.23691129}
ptw = {"diesel" : 10.21, "electric" : 0}
pm = {"diesel" : 0.583, "electric" : 0}

In [7]:
#defining column name varaibles

bus_type = ["30ft","40ft","60ft"]


#calculating electric bus emissions for different bus types in gm
for i in bus_type:
    p = "energy_"+i
    q = "e_emi"+i
    route_data[q] = route_data[p]*wtp["electric"]*52/1000
    
#calculating diesel bus emissions in gm 
a  = "d_emi"
route_data[a] = ((((route_data["VKT"]*0.621371*route_data["avg_rider"]*wtp["diesel"])/100000)+ (route_data["VKT"]*0.621371/route_data["fuel_economy"])*ptw["diesel"]/1000))*52

# #calculating PM2.5 emissions for diesel in gm
a  =  "pm_emi"
route_data[a] = route_data["VKT"]*pm["diesel"]

In [8]:
route_data.head()

,route_id,VKT,num_buses,avg_rider,energy_30ft,energy_40ft,energy_60ft,avg_speed,30ft_LOS,40ft_LOS,60ft_LOS,diesel_LOS,fuel_economy,e_emi30ft,e_emi40ft,e_emi60ft,d_emi,pm_emi
0,201,671.572,4.0,10.0,1391.904644,1768.149663,2428.823606,5.920670,no,no,no,yes,2.129226,17.147412,21.782520,29.921618,138.771094,391.526476
1,202,204.479,6.0,10.0,393.132635,499.785551,687.064708,5.179345,no,no,no,yes,1.996692,4.843153,6.157052,8.464216,44.355691,119.211257
2,210,533.152,4.0,11.0,1149.806222,1461.450040,2008.648337,7.328337,no,no,no,yes,2.371208,14.164908,18.004169,24.745316,104.494883,310.827616
3,211,804.990,9.0,17.0,1351.234773,1706.557173,2330.542098,6.300936,no,no,no,yes,2.195845,16.646384,21.023738,28.710850,191.687627,469.309170
4,212,189.424,2.0,17.0,341.131084,428.283673,581.364908,5.997131,no,no,no,yes,2.142695,4.202526,5.276192,7.162059,45.812361,110.434192

In [9]:
route_data.to_sql("mbta_e_data",con=engine, if_exists = 'replace')

In [10]:
city = "Boston"
country = "United States"

In [11]:
#Import effect factor data
query = "SELECT * FROM effect_factor ;"
ef = pd.read_sql(query, engine)

#collect effect factor for a given city 
eff = ef.loc[ef["City"] == city,["mean"]].values[0][0]

In [12]:
#Import intake fractions data
query = "SELECT * FROM intake_fractions ;"
inf = pd.read_sql(query, engine)

#collect intake fraction for a given city 
iff = inf.loc[inf["CityName"] == city,["iF_ppm"]].values[0][0]

In [13]:
#Import vsl fractions data
query = "SELECT * FROM vsl ;"
vsl = pd.read_sql(query, engine)

#collecting vsl data for a given country 
vs = vsl.loc[vsl["Country"] == country,["VSL USD million 2020"]].values[0][0]

In [14]:
route_data["e_impact"] = (route_data["pm_emi"]*iff*52*eff*vs)/(1000*1000000)

In [15]:
route_data

,route_id,VKT,num_buses,avg_rider,energy_30ft,energy_40ft,energy_60ft,avg_speed,30ft_LOS,40ft_LOS,60ft_LOS,diesel_LOS,fuel_economy,e_emi30ft,e_emi40ft,e_emi60ft,d_emi,pm_emi,e_impact
0,201,671.572,4.0,10.0,1391.904644,1768.149663,2428.823606,5.920670,no,no,no,yes,2.129226,17.147412,21.782520,29.921618,138.771094,391.526476,0.856253
1,202,204.479,6.0,10.0,393.132635,499.785551,687.064708,5.179345,no,no,no,yes,1.996692,4.843153,6.157052,8.464216,44.355691,119.211257,0.260710
2,210,533.152,4.0,11.0,1149.806222,1461.450040,2008.648337,7.328337,no,no,no,yes,2.371208,14.164908,18.004169,24.745316,104.494883,310.827616,0.679768
3,211,804.990,9.0,17.0,1351.234773,1706.557173,2330.542098,6.300936,no,no,no,yes,2.195845,16.646384,21.023738,28.710850,191.687627,469.309170,1.026361
4,212,189.424,2.0,17.0,341.131084,428.283673,581.364908,5.997131,no,no,no,yes,2.142695,4.202526,5.276192,7.162059,45.812361,110.434192,0.241515
5,214,322.743,4.0,40.0,544.630753,680.983114,920.342054,6.568696,no,no,no,yes,2.242199,6.709517,8.389295,11.338050,114.226454,188.159169,0.411497
6,215,1395.334,12.0,20.0,2161.350609,2718.171950,3696.158497,6.819996,no,no,no,yes,2.285286,26.626515,33.486212,45.534407,345.699171,813.479722,1.779048
7,216,807.525,4.0,18.0,1237.950480,1567.417746,2145.925622,8.105051,no,no,no,yes,2.499298,15.250791,19.309626,26.436488,181.735827,470.787075,1.029593
8,217,114.998,2.0,26.0,218.786761,274.744028,373.019999,6.939686,no,no,no,yes,2.305665,2.695319,3.384678,4.595378,31.911552,67.043834,0.146622
9,220,2756.083,7.0,18.0,3915.932731,4936.985155,6730.115766,10.125741,no,no,no,yes,2.814448,48.241891,60.820631,82.910901,579.528448,1606.796389,3.514001
10,221,74.948,2.0,12.0,124.897282,158.060413,216.297502,8.276027,no,no,no,yes,2.526976,1.538658,1.947207,2.664653,14.434107,43.694684,0.095559
11,222,1993.842,5.0,23.0,2616.254029,3295.400648,4488.021977,9.160976,no,no,no,yes,2.667242,32.230646,40.597316,55.289680,483.687584,1162.409886,2.542145
12,225,1479.408,4.0,28.0,3056.227631,3831.944344,5194.381756,5.499128,no,no,no,yes,2.054294,37.650851,47.207206,63.991599,451.728693,862.494864,1.886243
13,226,799.607,2.0,25.0,1713.363383,2156.449377,2934.540525,8.399351,no,no,no,yes,2.546824,21.107587,26.566135,36.151741,206.921012,466.170881,1.019498
14,230,1854.350,5.0,25.0,3366.430502,4231.808063,5751.607846,7.921780,no,no,no,yes,2.469423,41.472360,52.133282,70.856283,487.394485,1081.086050,2.364293
15,236,692.657,2.0,23.0,1449.444698,1823.766271,2481.257859,7.455959,no,no,no,yes,2.392520,17.856270,22.467683,30.567576,177.869424,403.819031,0.883136
16,238,1901.825,14.0,28.0,3639.111875,4562.969337,6185.476180,8.195297,no,no,no,yes,2.513931,44.831628,56.212985,76.201275,524.870709,1108.763975,2.424824
17,240,2698.432,11.0,35.0,5322.178789,6630.882784,8928.983719,8.762124,no,no,no,yes,2.604644,65.565981,81.688412,109.999607,830.040308,1573.185856,3.440496
18,245,373.227,3.0,16.0,750.315367,951.332318,1304.384023,7.492085,no,no,no,yes,2.398534,9.243425,11.719831,16.069212,82.206444,217.591341,0.475864

In [16]:
#sending resutls to database
route_data.to_sql("health_result", con=engine, if_exists ="replace")